### ISSUE TITLE
Backport Wireguard ListenPort fix in systemd

### ISSUE THREAD

**Issue by teemow** [flatcar/Flatcar#10]
In systemd 242 (in flatcar edge release 2261.99.0) there is a bug that the listen port of wireguard is always set randomly. This has been fixed upstream.

See: https://github.com/systemd/systemd/issues/12377

**Comment by dongsupark** [comment]
Yes exactly.
Systemd v242 has the bug w.r.t. Wireguard.
We noticed the issue in the past, and created a PR https://github.com/flatcar-linux/systemd/pull/5.
We will merge the PR, and create a new Edge release. Then it will be fixed.

However, backporting every patch is not ideal.
An underlying issue is that the systemd repo in Flatcar Linux is not automatically synchronized with the [upstream systemd-stable repo](https://github.com/systemd/systemd-stable). That has been always the case since the beginning of Container Linux. That's basically why such bug fixes are missing.
We are working on a new workflow to make it synced.

**Comment by teemow** [comment]
@dongsupark thanks for the detailed explanation. Sounds good :+1:

**Comment by dongsupark** [comment]
[Edge 2275.99.0](https://edge.release.flatcar-linux.net/amd64-usr/2275.99.0/) was released with the [backport](https://github.com/flatcar-linux/systemd/pull/5).
Please try it out, and let us know if it fixes the Wireguard issue.

**Comment by teemow** [comment]
@dongsupark thanks! works like a charm.
