### ISSUE TITLE
`emerge-gitclone` seems broken in 3033.3.11 SDK

### ISSUE THREAD

**Issue by da-x** [flatcar/Flatcar#1002]
This is what I am getting running `emerge-gitclone` under the SDK:

Output:

```
>> Starting git clone in /var/lib/portage/scripts
Cloning into '/var/lib/portage/scripts'...
remote: Enumerating objects: 272809, done.
remote: Counting objects: 100% (4240/4240), done.
remote: Compressing objects: 100% (1330/1330), done.
remote: Total 272809 (delta 1326), reused 4173 (delta 1298), pack-reused 268569
Receiving objects: 100% (272809/272809), 91.66 MiB | 2.45 MiB/s, done.
Resolving deltas: 100% (120672/120672), done.
>>> Git clone in /var/lib/portage/scripts successful
fatal: not a git repository: ../../../../.git/modules/sdk_container/src/third_party/coreos-overlay
fatal: could not reset submodule index
```

**Comment by da-x** [comment]
Just to be clear, this is tried under the container spawned using `sudo systemd-nspawn --image=flatcar_developer_container.bin` as suggested in [Building custom kernel modules | Flatcar Container Linux](https://www.flatcar.org/docs/latest/reference/developer-guides/kernel-modules/).

**Comment by tormath1** [comment]
Hello @da-x and thanks for the report,

We [recently](https://github.com/flatcar/scripts/pull/699) merged our main repositories (`flatcar/portage-stable` and `flatcar/coreos-overlay`) into `flatcar/scripts` and as a big change never comes alone it seems we missed to include this change in the latest release: https://github.com/flatcar/flatcar-dev-util/pull/15.

While it should be fixed in the next releases, could you try with this nightly build: http://bincache.flatcar-linux.net/images/amd64/3033.3.11+nightly-20230417-2100/ ?

**Comment by t-lo** [comment]
Hello @da-x ,

Please pardon the mishap - the version of `emerge-gitclone` shipped with the last releases is indeed unable to handle the new unified `scripts` repo. As Mathieu stated we've fixed this issue in `main` and in all release branches (channels) and will roll out a fix with the next patch release within at most 2 weeks.

Using last nightly's devcontainer as proposed above is indeed a good option to proceed.

Another workaround until the fix is rolled out would be to `wget` the newer version of `emerge-gitclone` used in both the nightly devcontainer as well as in the upcoming LTS 3033 release (ref [9240efb80504da934b2315cc89bddb81b739b214](https://github.com/flatcar/scripts/blob/flatcar-3033/sdk_container/src/third_party/coreos-overlay/coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild#L13)). Right after the `sudo systemd-nspawn ...` step, run
```shell
wget https://raw.githubusercontent.com/flatcar/flatcar-dev-util/9240efb80504da934b2315cc89bddb81b739b214/emerge-gitclone
```
then use the `emerge-gitclone` version just downloaded instead of the one shipped in the devcontainer.

**Comment by da-x** [comment]
Thanks! It's very helpful. I'll update

**Comment by da-x** [comment]
Workaround worked. Thanks

**Comment by tormath1** [comment]
Hello @da-x, for your information we just released a new set of maintenance releases including the fix for this issue (https://www.flatcar.org/releases#release-3033.3.12). Everything should be back on track from now: happy hacking on Flatcar and feel free to join the [#flatcar](https://app.element.io/#/room/#flatcar:matrix.org) Matrix channel to share your experiments. :D
