### ISSUE TITLE
99-default.rules reappear after update

### ISSUE THREAD

**Issue by gradientsearch** [flatcar/Flatcar#1023]
## Description

The 99-default.rules come back after update. Since the ignition file runs only one time at first boot the updates place the original 99-default.rules back on disk . This does seem to be a bug. I think a solution is to move the 99-default.rules to a different directory that does not get overwritten on update. We are open for other suggestion too.

## Impact

The audit rules are not triggering because the 99-default.rules includes a rule that ignores all rules.

## Environment and steps to reproduce

1. **Set-up**: Nebraska
2. **Task**: updates
3. **Action(s)**: Write ignition file that overwrites 99-default.rules with an empty file.
4. **Error**: On update the original 99-default.rules appear.

## Expected behavior
On update the 99-default.rules is not changed.
## Additional information

https://github.com/flatcar/coreos-overlay/pull/2545
https://github.com/flatcar/flatcar-docs/pull/296

**Comment by pothos** [comment]
Thanks for creating an issue, I guess this only happened on Stable where systemd-tmpfile would recreate a deleted file after each reboot. The solution would be to create an empty file or a file with a comment (as shown in the docs PR).
In Flatcar Beta/Alpha this problem is solved and you can delete the file and it won't be created again on reboot because instead of  systemd-tmpfile rules provide the OS defaults through the lowerdir of an overlay mount.

**Comment by gradientsearch** [comment]
thanks @pothos
