### ISSUE TITLE
Deis workflow is in maintenance mode

### ISSUE THREAD

**Issue by nocheinlarry** [flatcar/Flatcar#1224]
While clicking on Deis workflow, the website redirects to AKS from Microsoft. Website no longer available. There is a security warning.
Recommendation to remove the link or link to the github repos.

**Comment by jepio** [comment]
Hi @nocheinlarry, this repo is for issues related to Flatcar (the open source project).

Can you paste the url you are visiting and which link you would like to see removed?

**Comment by tormath1** [comment]
I think it's about this one: https://github.com/flatcar/flatcar-website/blob/d80b361b2c8eae2b4f47b5da94c0fb7e5861830a/content/docs/latest/reference/integrations.md?plain=1#L12 (https://www.flatcar.org/docs/latest/reference/integrations/). 
Deis project is archived since 2021: https://github.com/deis/workflow

**Comment by nocheinlarry** [comment]
Thanks @tormath1 for making the PR. I'm new to flatcar docs and was not reading the contribution and workflow guide proposing a change to docs. Thank you guiding me thru, thank you @jepio as well.
