### ISSUE TITLE
GCP image of stable has disapeared

### ISSUE THREAD

**Issue by gamethis** [flatcar/Flatcar#1225]
## Description

Hi we were using flatcar stable [https://www.flatcar.org/releases#release-3374.2.5 [flatcar.org]](https://urldefense.com/v3/__https://www.flatcar.org/releases*release-3374.2.5__;Iw!!M-nmYVHPHQ!OXzOk_gCpzUPtQ3HtSbMXnN0QKrfy_NROW9gzYcANeJRLVm2Ti6P5pyhDkmDZP8vHD6uRMRMBrB7A2xcfIkmkOMRu-RF$) in GCP
On Thursday we noticed the image became unavailable for use
gcloud compute images describe "projects/kinvolk-public/global/images/flatcar-stable-3374-2-5"
 
ERROR: (gcloud.compute.images.describe) Could not fetch resource:
 - Required 'compute.images.get' permission for 'projects/kinvolk-public/global/images/flatcar-stable-3374-2-5'

## Impact

this is causing production versions of flatcar in gcp to not be able to scale.

## Environment and steps to reproduce
GCP us regions

## Expected behavior

Images in gcp should be able to scale or deploy new.

## Additional information

Want to know if this is intentional or if there is a stated timeline for these items to be removed from GCP

**Comment by t-lo** [comment]
Thank you for reaching out. Could you please double-check if you are using the "Flatcar Container Linux Pro" offer on GCP? That offer has been discontinued in favour of the regular "Flatcar Container Linux".

If you are still using "Pro", then resolving this issue can be as easy as switching offers - all "Pro" features have been ported and the regular offer has been shipping the exact same bits as the "Pro" offer for some time.

We will investigate the disappearance on our end - there has been no conscious de-publishing of that version as far as I know.

**Comment by t-lo** [comment]
We also publish all our images on our HTTP server; the respective release you are using is here: https://stable.release.flatcar-linux.net/amd64-usr/3374.2.5/ (file [flatcar_production_gce.tar.gz](https://stable.release.flatcar-linux.net/amd64-usr/3374.2.5/flatcar_production_gce.tar.gz)). 

As a stop-gap measure to stay operational while we investigate you could consider self-hosting that release image on GCP. Instructions for self-hosting are here: https://www.flatcar.org/docs/latest/installing/cloud/gcp/#uploading-an-image

**Comment by gamethis** [comment]
> Thank you for reaching out. Could you please double-check if you are using the "Flatcar Container Linux Pro" offer on GCP? That offer has been discontinued in favour of the regular "Flatcar Container Linux".
> 
> If you are still using "Pro", then resolving this issue can be as easy as switching offers - all "Pro" features have been ported and the regular offer has been shipping the exact same bits as the "Pro" offer for some time.
> 
> We will investigate the disappearance on our end - there has been no conscious de-publishing of that version as far as I know.

We have confirmed we are not using the pro offering of flatcar in gcp

**Comment by gamethis** [comment]
> We also publish all our images on our HTTP server; the respective release you are using is here: https://stable.release.flatcar-linux.net/amd64-usr/3374.2.5/ (file [flatcar_production_gce.tar.gz](https://stable.release.flatcar-linux.net/amd64-usr/3374.2.5/flatcar_production_gce.tar.gz)).
> 
> As a stop-gap measure to stay operational while we investigate you could consider self-hosting that release image on GCP. Instructions for self-hosting are here: https://www.flatcar.org/docs/latest/installing/cloud/gcp/#uploading-an-image

I appreciate the input, unfortunately to fix this it would also require a change during a freeze..  We will definitely look at this as our route going forward with new releases upgrades.

**Comment by t-lo** [comment]
> I appreciate the input, unfortunately to fix this it would also require a change during a freeze.. We will definitely look at this as our route going forward with new releases upgrades.

Makes sense. Just to add more information, the risk of that change would be rather low as far as the OS image is concerned because the image on the HTTP server is bit-by-bit identical to the image published to GCP marketplace.

But of course this would imply a change in your provisioning automation, so the overall risk is not zero.

**Comment by chillerm** [comment]
Hey @t-lo,

Assuming you plan to re-publish the image, do you know about when it would be available?  We have some decent hurdles to jump internally to get any change on our end made and were just curious if this is something that would be able to be done in hours/days/weeks, just to set our own expectations.  Thanks for the quick responses and great support!


On a side note... I just watched a [presentation](https://archive.fosdem.org/2022/schedule/event/modding_the_immutable_how_to_extend_flatcar/) from you this morning.  Quite serendipitous.

**Comment by t-lo** [comment]
We're currently looking into re-publishing the image and will keep this issue updated. We understand the severity of the impact on your end and are prioritising finding a solution. We don't have an overall ETA yet as we're still investigating options but will have a date for a date by tomorrow the latest.

Re the FOSDEM presentation - we are pushing quite a bit of effort into improving the Flatcar developer experience, thanks :)  The presentation basically walks through the reference docs here: https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/ .
We did a slightly more up-to-date workshop at FrOSCon 2023, sources are here: https://github.com/flatcar/flatcar-demos/tree/main/froscon-2023

If you "just" want to extend the base image / compose more features into images at provisioning time, sysext is the new tool of choice. Here's a presentation from WASMCon earlier this year where two WASM fans used that mechanism to compose a WASM stack plus OS: https://www.youtube.com/watch?v=dEeLo-LKf88

**Comment by t-lo** [comment]
Hello @chillerm and @gamethis ,

As promised here's our status update. The un-publishing was caused by an over-eager cleanup logic in our publishing automation; we have tracked down and fixed the issue. We have also adapted out publishing tooling for re-publishing old releases and are currently in the process of re-publishing stable-3374.2.5 to the GCP marketplace. We expect the release to become available again by tomorrow by the latest.

We are very sorry for the inconvenience.

**Comment by sayanchowdhury** [comment]
Hello @gamethis, @chillerm 

We've republished the image, `stable-3374.2.5` and should be available on GCP. Please check the availability on your end and let us know if you face any issues.

```
❯ gcloud compute images describe "projects/kinvolk-public/global/images/flatcar-stable-3374-2-5"                                                          
archiveSizeBytes: '538658432'
creationTimestamp: '2023-11-01T07:18:32.212-07:00'
deprecated:
  replacement: https://www.googleapis.com/compute/v1/projects/kinvolk-public/global/images/flatcar-stable-3510-2-0
  state: DEPRECATED
description: The Stable channel should be used by production clusters. Versions of
  Flatcar Container Linux are battle-tested within the Beta and Alpha channels before
  being promoted., 3374.2.5, amd64-usr published on 2023-11-01
<-snip->
```

As @t-lo mentioned, the un-publishing happened because we cleanup the old images so to mitigate this we would be refactoring the logic make it a better user experience. I would also recommend to upgrade to the latest stable image as soon as it's possible for you folks.

**Comment by gamethis** [comment]
@sayanchowdhury thank you we have confirmed the image is working.
Do you have plans around future state ie... keep stable available for 6 months or anything like that?
we will definitely move as soon as we can to latest stable.

**Comment by t-lo** [comment]
@gamethis We currently do not have a retention policy for GCP - as discussed above this issue was caused by over-eager garbage collection. Following this incident we'll start a discussion in the maintainers team on officially documenting a retention policy for GCP our users can rely on.

We have something similar [in place for the AWS marketplace images and regional public AMIs](https://www.flatcar.org/docs/latest/installing/cloud/aws-ec2/) - these have a minimum life time of 9 months. I don't want to preempt the maintainer discussion but I could imagine our future GCP retention policy might follow similar lines.

Lastly, please note that the main reason for retention is that each image inflicts recurring monthly cloud provider costs, so images need to be removed eventually to keep cloud costs constant. The images published on our HTTPS release servers do not incur ongoing costs will never be removed, so self-hosting images that have been un-published from marketplaces always remains an option.

**Comment by gamethis** [comment]
Thank you I appreciate the information and the support.
