### ISSUE TITLE
No dig binary in Alpha 2492.0.0 ARM

### ISSUE THREAD

**Issue by johananl** [flatcar/Flatcar#123]
**Description**

Seems like Alpha `2492.0.0` **ARM** doesn't contain the `dig` binary.

**Impact**

Cannot use `dig` in Lokomotive CI pipelines.

**Environment and steps to reproduce**

1. **Set-up**: Deploy an ARM machine on Packet using the web UI with the following iPXE script: `https://alpha.release.flatcar-linux.net/arm64-usr/current/flatcar_production_packet.ipxe`
2. **Task**: Run `dig` from a shell.
3. **Action(s)**: Run `dig` from a shell.
4. **Error**: `dig: command not found`

**Expected behavior**
Expected to see `dig` output.

**Comment by t-lo** [comment]
Validated that `dig` is included and operational in the `AMD64` image; not having it on ARM is a bug.

**Comment by dongsupark** [comment]
It is an interesting can of worms.
So far what I have found out is like that.

`net-dns/bind-tools` is not installed for ARM, because it is intentionally disabled in [package.provided](https://github.com/flatcar-linux/coreos-overlay/blob/12639e0d4e44d82a8b6df526c94ad98d80f5af40/profiles/coreos/arm64/package.provided#L6).
The code was added via commit [b37d1376](https://github.com/flatcar-linux/coreos-overlay/commit/b37d1376cd13290ea708bd2e8a17dcce5e87064a), but it does not explain why there is a build error with bind-tools for ARM.

When I remove bind-tools from `package.provided`, then try to install bind-tools, then it fails like that:

```
checking for gssapi/gssapi.h... no
configure: error: gssapi.h not found
```

However, the `/usr/include/gssapi/gssapi.h` is actually already there, as `app-crypt/mit-krb5` is installed for ARM.
So I suppose, we need to specify a correct path for gssapi when the ebuild runs a configure script.
That's all I have now.

**Comment by dongsupark** [comment]
Today I have looked into this issue again.

As expected, there were good reasons for CoreOS Container Linux to have not enabled it for ARM.
The upstream `net-dns/bind-tools` has its own complicated logic for detecting runtime library linkage, e.g. gssapi, gssapi_krb5, openssl, etc. Even after specifying the prefixes `/build/arm64-usr/` etc, it still does not find correct library paths. Removing the logic in `configure.ac` still does not resolve the issue, as it afterwards anyway fails during the build step. In theory we could fix all the places in the bind source code, but I could not manage to do it.

As plan B, I would suggest simply disabling the USE flag `gssapi` for `net-dns/bind-tools` in case of ARM. In that case, its build simply passes. Of course we don't know what could happen if there would be any runtime case that bind-tools really requires gssapi. Though after all, providing such a limited bind-tools would be still better than having no bind-tools at all.

**Comment by dongsupark** [comment]
Filed PRs.
* https://github.com/flatcar-linux/coreos-overlay/pull/411
* https://github.com/flatcar-linux/coreos-overlay/pull/412

**Comment by dongsupark** [comment]
Alpha 2513.1.0 was released with a dig binary for ARM.
Test with its qemu image:

```
core@localhost ~ $ cat /etc/os-release 
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2513.1.0
VERSION_ID=2513.1.0
BUILD_ID=2020-06-29-1540
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2513.1.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="arm64-usr"

core@localhost ~ $ dig -v
DiG 9.11.2-P1
```

Edge release is still pending, the next release will include the same bind-tools as Alpha.
