### ISSUE TITLE
Why Beta version number is lower than that of Stable?

### ISSUE THREAD

**Issue by comphilip** [flatcar/Flatcar#126]
After 2 months waiting, new version of flatcar finally release on May 26, 2020. While in [release page](https://www.flatcar-linux.org/releases/), Beta version number is lower then Stable version number, why?

**Comment by chrskhl** [comment]
In the most recent release of CoreOS Container Linux which we have been following, they created a bit of a pickle for us when they spun releases with versions 2512.3.0, 2513.2.0, 2514.1.0 for Stable, Beta, and Alpha channels, respectively. This does not follow their standard versioning and I'm not sure 100% why they did that other than this being their final release.

The fact is that each of those CoreOS releases are identical. You can see that by running these files in your favorite diff tool.
https://stable.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt
https://beta.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt
https://alpha.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt

This is a confusing situation and we tried to deal with that the best we could. Because the Stable and Beta releases are identical for this release cycle, we decided to make the Beta release follow behind the Stable version-wise so that the Stable channel would be the "preferred" channel (highest version). This is logical as within the same release series (same major number) the Stable will always be the higher version. For example, XXXX.Y.Z in Beta turns into XXXX.(Y+1).Z  when promoted to Stable.

However, our Alpha is independent of the CoreOS Container Linux releases and includes significant updates for major components (Kernel, systemd, Docker, etc.). Thus, this received a new major number. You should see another Alpha release next week. This release is targeted to eventually land in the Stable channel. So in about 2 or so weeks you'll see that promoted into the Beta channel and this current situation will be resolved.

So the gist of it is that the situation is because of the weirdness in the last CoreOS Container Linux release versions and will be rectified in the next couple weeks once Alpha gets promoted to Beta.

**Comment by comphilip** [comment]
Thanks for explaining, according to [CoreOS Container Linux End-of-life announcement ](https://coreos.com/os/eol/), I think it is the final release of CoreOS Container linux. Looking forward to next release of flatcar with updated components: kernel, docker and so on.
