### ISSUE TITLE
libtool is missing from the images.

### ISSUE THREAD

**Issue by jhaprins** [flatcar/Flatcar#1292]
## Description

During a build in GitHub I noticed that the build was failing because it tried to build libtool, which in itself was strange because it should have been available in the buildtree to begin with.

## Impact

Building all kind of packages fails.

## Environment and steps to reproduce

Try to build zfs in the github build environment and it fails.
Example log files: https://github.com/jhaprins/sysext-bakery/actions/runs/7193136843/job/19590965212

## Expected behavior

A successful build.
https://github.com/jhaprins/sysext-bakery/actions/runs/7169017331/job/19518446386

## Additional information

Please add any information here that does not fit the above format.

**Comment by t-lo** [comment]
Thank you for the report! Indeed the libtool binpackage appears to have vanisdhed.

3732.0.0 still has the libtool binpkg (https://bincache.flatcar-linux.net/boards/amd64-usr/3732.0.0/pkgs/sys-devel/), 3745.0.0 doesn't (https://bincache.flatcar-linux.net/boards/amd64-usr/3745.0.0/pkgs/sys-devel/).

Working on the latest main nightly, I see that libtool is a dependency of `board-packages`:
```
emerge-amd64-usr --pretend --verbose --emptytree coreos-devel/board-packages
```
lists libtool.

But!

```
emerge-amd64-usr --pretend --verbose coreos-devel/board-packages
```
does not list libtool. So apparently it's installed? However, libtool is not available as a binpkg included in the SDK in `/board/<arch>/var/lib/portage/pkgs`. I.e. it's not part of the board toolchain.

And it's not being built by `build_packages` either. So that results in no binpkg for `libtool` All binpkgs required by OS image and devcontainer should actually be built and exported by `build_packages`, but apparently are not. And more packages than just `libtool` are affected.
