### ISSUE TITLE
Alpha 2513.0.0: unable to install from ISO using TTY

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#131]
**Description / Impact**

The latest Alpha release 2513.0.0 cannot be installed via a serial console from the ISO image.

**Environment and steps to reproduce**

1. **Set-up**: Download Alpha 2513.0.0 ISO. Attach to virt-manager.
2. **Task**: Install Flatcar Container Linux to virtual hard disk.
3. **Action(s)**:
  a. Boot from the ISO
  b. log in via serial console
  c. install to hard disk 
4. **Error**: after a. Output stops mid-boot, no login prompt appears.

**Expected behavior**
Image boots, login prompt appears on serial console

**Additional information**
`/usr/lib64/systemd/system/getty.target.wants/getty@tty1.service -> ../getty@.service` is missing.

**Comment by margamanterola** [comment]
Thanks for filing this Thilo!

"Stops mid-boot" is not exactly correct, the machine boots just fine and the output goes all the way to the end, but the login prompt is indeed missing.

The issue is that once it finishes booting, there's no tty in the current console. When using this interactively, one can send ctrl-alt-f2 and there's an interactive console ready to be used.  The problem is that if this is used in a script, the interactive console isn't there.

**Comment by margamanterola** [comment]
This issue seems to be what we're experiencing: https://github.com/systemd/systemd/issues/12345 (whoa, cool number! :)

The suggested workaround is to run: `sudo systemctl enable getty@tty1.service`, I'm not sure where we would place that, though.  Reading the [NEWS](https://github.com/systemd/systemd/blob/1fa3ba909605c13761af69ae0ba1653292b6e730/NEWS#L244) file that they updated, they also mentioned running `systemctl preset-all` is recommended after installing systemd... So maybe we could add that to the ebuild?

**Comment by t-lo** [comment]
I don't think we have a good place for running this workaround for the ISO given that we also don't ship ignition with the ISO (see #51).

**Comment by margamanterola** [comment]
I think we need to fix this system-wide, not just for the iso. There might be other unintended consequences of how the systemd installation changed (the NEWS file I linked lists several services and targets that are no-longer auto-enabled).

I think running `systemctl preset-all` after installing systemd is probably what we want, to ensure the installation is complete.

**Comment by t-lo** [comment]
Fully agree with the need for a system-wide fix. I was merely commenting on the viability of the work-around for the case reported.

**Comment by dongsupark** [comment]
Alpha 2513.1.0 was released with the bug fix https://github.com/flatcar-linux/coreos-overlay/pull/400.
I have just tested an ISO installation with the release.
It works well as expected.
Thanks!
