### ISSUE TITLE
Add SHA256 hashes to DIGESTS.asc files

### ISSUE THREAD

**Issue by ryanm101** [flatcar/Flatcar#132]
My ansible build scripts use sha256 to verify the flatcar images for pxe etc. 
https://stable.release.flatcar-linux.net/amd64-usr/2345.3.1/flatcar_production_pxe.DIGESTS.asc

Having the extra hash would be very useful

**Comment by pothos** [comment]
Hello,
thanks for the ticket. Yes, since it's well-documented how to create MD5 and SHA1 collisions those hashes are only useful for checking accidental corruption. Not sure if SHA256 is what we want to settle on because it's 20 years old now already but it could be one additional entry. Fortunately Ansible looks quite flexible in supporting many hash algorithms: https://docs.ansible.com/ansible/latest/modules/get_url_module.html#parameter-checksum
Additional algorithms are available via https://docs.python.org/3/library/hashlib.html

**Comment by ryanm101** [comment]
Hi thanks for the quick response, 
yea not suggesting it is the best primary solution but having the extra SHA256 would just provide an extra option and speed up my workflow considerably, moving off SHA256 is something I may look into in the future but it's at least 6-12months out on my todo list as we are also running an old version of ansible (I hate legacy systems :( ) and there are likely other dependencies on that hash that i've not yet come across.

**Comment by jepio** [comment]
We have sha512, sha1 and md5 available. Did you ever manage to move off SHA256? I want to say this issue can be closed.

**Comment by tormath1** [comment]
Hi @ryanm101, do the signatures proposed work for you (sha512, sha1 and md5)? I'll close this issue for now since it's been almost 2 years. Feel free to re-open if it remains a major issue for you, thanks! :)

**Comment by krnowak** [comment]
When adding digests generation to the new pipeline, I actually added a TODO about dropping sha1 and md5 in favor of blake2, while keeping sha512 as is. Maybe we could also use whirlpool. But maybe it's too early for such move?

**Comment by pothos** [comment]
If we don't really have to drop something, I think it's good to drag it along for backwards compatibility. Regarding modern hash functions, [b3sum](https://github.com/BLAKE3-team/BLAKE3) is what comes to mind ;)
