### ISSUE TITLE
Ignition ignores non-transpiled config without warnings or errors

### ISSUE THREAD

**Issue by rgl** [flatcar/Flatcar#135]
**Description**

After install, flatcar cannot boot because it does not seem to find the disk partition with an UUID that ends in `000000000001`:

![image](https://user-images.githubusercontent.com/43356/84207475-5f1aac80-aaa9-11ea-9ac5-d859a50794dd.png)

After flatcar-install (and before reboot), these are the partition UUIDs:

![image](https://user-images.githubusercontent.com/43356/84207551-8b362d80-aaa9-11ea-947f-e3a05aa1d8ba.png)

And this is the information returned by `udevadm info --name sda` (which shows the UUID that ends in `000000000001`):

![image](https://user-images.githubusercontent.com/43356/84207620-b02aa080-aaa9-11ea-84c0-765a7273b958.png)

**Impact**

Cannot use flatcar.

**Environment and steps to reproduce**

I'm trying to use packer to install flatcar from the iso into a qemu/kvm VM as defined at the [rgl/flatcar-linux-vagrant](https://github.com/rgl/flatcar-linux-vagrant) repository.

To reproduce the problem, clone the referred repository and type `make build-libvirt`.

**Comment by pothos** [comment]
Hi,
thanks for creating an issue with all necessary information.

I've not used this scenario myself and don't know if it is supposed to work like that. One first problem I see is that you need to convert the YAML Container Linux Config into a JSON Ignition config.
See https://docs.flatcar-linux.org/container-linux-config-transpiler/doc/getting-started/
About the rest: We will need to try it out and see where the problem is…

**Comment by rgl** [comment]
Thanks for noticing the ignition snafu! I've fixed it at https://github.com/rgl/flatcar-linux-vagrant/commit/375f36c860a2eed91b255e62553c1e20152782fa and now flatcar can successfully boot!

I wonder, was that supposed to happen? Shouldn't flatcar-install validate the file and abort?

**Comment by pothos** [comment]
Making a validation in flatcar-install is a great idea and maybe Ignition could also do better at detecting invalid configs.

What normally happens is that Ignition ignores all non-Ignition configs and tells cloud-init to run after bootup because cloud-init takes care of executing cloud configs and shell scripts passed as config.
Now in your case it was some other YAML and I need to check what exactly goes on.

**Comment by tormath1** [comment]
I think this issue can be closed, and we now have a mechanism to display Ignition errors during the boot: https://github.com/flatcar-linux/bootengine/pull/28. :)
