### ISSUE TITLE
Flatcar vs CoreOS versioning

### ISSUE THREAD

**Issue by tobgu** [flatcar/Flatcar#144]
**Current situation**
The latest stable Flatcar release still has a lower version number than the last CoreOS release had. This prevents the update engine from picking up Flatcar. Our plan was to follow https://docs.flatcar-linux.org/os/update-from-container-linux/ but hoping to avoid setting COREOS_RELEASE_VERSION (which I guess is the solution to this?) and just have the OS update as normal when the next version of Flatcar was available.

**Impact**
OS not updated to Flatcar.

**Ideal future situation**
New release of Flatcar with a higher version number than last CoreOS container Linux version.

**Additional information**
This is not a stopper in any way, I would mostly like to get some clarity on how the versioning is stepped and how it relates to the previous versioning scheme used by CoreOS.

**Comment by t-lo** [comment]
Hello @tobgu,

thank you for reporting this issue. CoreOS introduced a number of changes with the final round of releases which we did not ingest (banner calling out EOL, and a change in the way major release version numbers are used). We detached Flatcar Container Linux from CoreOS upstream before that change.

New releases of Flatcar Container Linux will of course use higher release numbers, making this a transient issue. To work around this please consider re-setting the release version as [described in our migration docs](https://docs.flatcar-linux.org/os/update-from-container-linux/#modifying-the-configuration-files), like you mentioned in the issue descriotion.

**Comment by pothos** [comment]
Just a small addition on how the migration is supposed to be done: You should force an update after running the script. Of course you can delay the reboot but if you remove the step of triggering an update and waiting for it to happen later, and the machine accidentally reboots before the update is applied, it will not get updates after the reboot because you already overwrote the server URL but the bind mount of the key is gone. So please force an update as part of the migration script even if the Flatcar version was equal to or higher than the CoreOS version.

**Comment by tobgu** [comment]
Thanks to both of you for responding! We'll review how to do the update before proceeding.
