### ISSUE TITLE
[Blog] What's new in Stable 3975.2.0

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1480]
As we near to the next major Stable release, I'm creating this issue to accumulate ideas for a "What's new" blog post for our blog, which would list down all the changes that are coming into the next Stable release.

The blogpost would be published soon after the next major Stable release.

It would great if folks can share a title/snippet of the feature/bug fix that is going to be present in next major Stable.

/cc @flatcar/flatcar-maintainers

**Comment by tormath1** [comment]
### New vendors

During the last months, we continued to invest on Flatcar support on cloud providers and enhance the existing support with better documentation and user experience. We added Flatcar support to Hetzner and Scaleway as well as KubeVirt images.

### Sysext

Since a while now Docker and Containerd are available on Flatcar as sysext images. The Flatcar team now provides official sysext images than can be enabled at boot on Flatcar, those images are built in Flatcar CI and are officially maintained. From this Stable, you will be able to run ZFS or Podman systemd sysext extensions and more will follow (e.g Python). Flatcar sysext images are now split in 2 types:
- Official:
  - enabled: Docker, Containerd, OEM
  - disabled: Podman, ZFS
- Community supported: from the Flatcar sysext-bakery: https://github.com/flatcar/sysext-bakery

Browse the documentation for more information: https://www.flatcar.org/docs/latest/provisioning/sysext/#types-of-systemd-sysext-images 

### Kernel

In this Stable we bump the Kernel version from 6.1 stream to 6.6. 

### Metrics

More than 2000 commits on Stable (I just counted `scripts` repo... so it's more with the other repos) 

```
$ git rev-list --count flatcar-3815..flatcar-3975
2059
```

**Comment by tormath1** [comment]
Blogpost is out: https://www.flatcar.org/blog/2024/08/whats-new-in-stable-3975.2.0/ thanks for driving this :D
