### ISSUE TITLE
udev rule shows red in the journalctl

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#169]
**Description**

```
Aug 23 21:13:35 localhost systemd-udevd[260]: /usr/lib64/udev/rules.d/50-udev-default.rules:39 Unknown group 'render', ignoring
Aug 23 21:13:35 localhost systemd-udevd[260]: /usr/lib64/udev/rules.d/50-udev-default.rules:40 Unknown group 'render', ignoring
```
Though in the journal this shows in RED.

**Impact**

This does not seem to block anything, just that the udev rule is ignored.

**Environment and steps to reproduce**

1. **Set-up**: fresh install of beta (2513.3.0)
2. **Task**: look through `journalctl`
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
4. **Error**: [describe the error that was triggered]

**Expected behavior**
no RED in the journal ;-)

![Screenshot from 2020-08-24 08-29-09](https://user-images.githubusercontent.com/67049/91044833-ee812780-e5e3-11ea-9c9f-f92e978f811a.png)

**Comment by t-lo** [comment]
Seems to affect Alpha, Beta, and (in some variation) Stable. The message in Stable is `Specified group 'render' unknown`.

**Comment by t-lo** [comment]
The system group "render" was missing, but is referenced in udev rules (for `/dev/dri`). In order to fix the error message the group needs to be added to both OS image and initramfs.

PRs to address the issue:
* [x] PR for baselayout to add the group to the initramfs: https://github.com/flatcar-linux/baselayout/pull/5
* ~PR for portage-stable to provide `acct-group/render`:  https://github.com/flatcar-linux/portage-stable/pull/98~ (not needed after all)
* [x] main PR  in coreos-overlay to wrap up everything (has description of the changes and instructions for testing): https://github.com/flatcar-linux/coreos-overlay/pull/543
