### ISSUE TITLE
remove vimdiff (or compile with diff feature)

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#221]
**Description**

went to use `/usr/bin/vimdiff` and get the error:

```shell
core@flatcar-local ~ $ vimdiff cluster.yml xx
This Vim was not compiled with the diff feature.
```

**Impact**

confusion or lack of vimdiff or both :smile_cat: 

**Environment and steps to reproduce**

2605.6.0

**Comment by dongsupark** [comment]
`vimdiff` is not installed because the `minimal` USE flag is [enabled](https://github.com/flatcar-linux/coreos-overlay/blob/cf7b010ace6a47cb4f0d6288f9307f29c617a454/profiles/coreos/targets/generic/package.use#L5) for `app-editors/vim`.
The symlink `vimdiff` is still created because upstream Gentoo [does](https://github.com/gentoo/gentoo/blob/22be0a20b032405eaa17774c3435b30104dc9575/app-editors/vim/vim-9999.ebuild#L279) so. Not sure why.
+1 on removing the symlink.

**Comment by dongsupark** [comment]
Filed PRs:
* https://github.com/gentoo/gentoo/pull/18496
* https://github.com/kinvolk/coreos-overlay/pull/727

**Comment by dongsupark** [comment]
Gentoo PR https://github.com/gentoo/gentoo/pull/18496 was merged as well.
