### ISSUE TITLE
Add CONFIG_DEBUG_INFO_BTF=y

### ISSUE THREAD

**Issue by iaguis** [flatcar/Flatcar#225]
**Current situation**

Currently running [BTF/CO-RE BPF programs](http://www.brendangregg.com/blog/2020-11-04/bpf-co-re-btf-libbpf.html) on Flatcar is not supported.

**Impact**

This means running BPF programs on Flatcar require access to the kernel headers, LLVM, Clang... which makes it very inconvenient.

**Ideal future situation**

`CONFIG_DEBUG_INFO_BTF` is enabled in the Flatcar kernel.

**Additional information**

Flatcar [has added this option](https://github.com/flatcar-linux/Flatcar/issues/13) to the Edge channel already.

**Comment by dongsupark** [comment]
I wanted to enable the option in the upcoming Alpha release, but realized I could not, because of the exact same issue we had in the Edge channel.
To build BTF, we need `dev-util/dwarves` that includes `pahole`. However, current Alpha does not have it.
We need to first import `dev-util/dwarves` and its dependencies, just like we did in the PRs:
https://github.com/kinvolk/coreos-overlay/pull/164 and https://github.com/kinvolk/portage-stable/pull/27 .

Then release an Alpha SDK in this week.
Based on the SDK, we can enable the kernel config `CONFIG_DEBUG_INFO_BTF`.

**Comment by dongsupark** [comment]
Filed PRs for dwarves:
* https://github.com/kinvolk/coreos-overlay/pull/690
* https://github.com/kinvolk/portage-stable/pull/126

**Comment by dongsupark** [comment]
Alpha 2697.0.0 was released, and its SDK includes dwarves (pahole).
So it is possible to build Kernel with `CONFIG_DEBUG_INFO_BTF` enabled.
I pushed a branch to https://github.com/kinvolk/coreos-overlay/tree/dongsu/kernel-config-btf . With the branch, everything works in case of amd64.

However, it uncovers a hidden issue in arm64.
Kernel build fails like:

```
+ pahole -J .tmp_vmlinux.btf
PAHOLE: Error: Found symbol of zero size when encoding btf (sym: '__kvm_nvhe_arm64_ssbd_callback_required', cu: '../source/arch/arm64/kernel/cpu_errata.c').
PAHOLE: Error: Use '-j' or '--force' to ignore such symbols and force emit the btf.
../source/scripts/link-vmlinux.sh: line 141: 1929102 Segmentation fault      (core dumped) LLVM_OBJCOPY=${OBJCOPY} ${PAHOLE} -J ${1}
```

It seems to happen only with Kernel 5.9.
Issue reported to upstream pahole, and the maintainer [replied](https://www.spinics.net/lists/kernel/msg3703763.html) that it was fixed via commit [2e719cca6672](https://git.kernel.org/pub/scm/devel/pahole/pahole.git/commit/?id=2e719cca667212840359820fa87faff2d8f7e1fc). However, the fix is not included in any dwarves/pahole release.
I will stop looking into the issue here.

**Comment by pothos** [comment]
Oh, I thought `CONFIG_DEBUG_INFO_BTF` was set already, it's in the release notes

**Comment by dongsupark** [comment]
dwarves [1.19](https://git.kernel.org/pub/scm/devel/pahole/pahole.git/tag/?h=v1.19) was released with the bug fix included.
Created a PR for updating dwarves to 1.19. https://github.com/kinvolk/portage-stable/pull/131

**Comment by dongsupark** [comment]
Created a PR https://github.com/kinvolk/coreos-overlay/pull/753, to enable BTF.
It is now possible to do so, as Alpha 2723.0.0 includes dwarves 1.19.

**Comment by dongsupark** [comment]
https://github.com/kinvolk/coreos-overlay/pull/753 was merged, will be included in the next Alpha.
