### ISSUE TITLE
PXE boot install fails to create bootloader

### ISSUE THREAD

**Issue by silencej** [flatcar/Flatcar#226]
**Description**

iPXE boot flatcar with root=LABEL=ROOT. lsblk shows /dev/sda1 is mounted to /, but /boot is empty
And booting with disk fails after rebooting.

**Environment and steps to reproduce**

The flatcar version is 2605.7.0, BUILD_ID 2020-10-23-1713

**Comment by pothos** [comment]
Setting the `root=` argument¹ only means that instead of a tmpfs the root filesystem you specified is used. This is only needed if you want to preserve some state and thus not used by default, e.g., as in https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_packet.ipxe
The `root=` argument does not install to disk, you have to run `flatcar-install` for that (e.g., with `-d /dev/sda` or `-s` and possibly a custom Ignition config via `-i`).

¹ https://docs.flatcar-linux.org/os/booting-with-ipxe/

**Comment by silencej** [comment]
I see. If users can specify one more kernel option on how to install to disk directly, it will be very convenient to automate the installation.

**Comment by silencej** [comment]
@pothos Another problem, since I have setup base linuz images and ignition in my local DNS server, I prefer to use them directly to install the OS. However flatcar-install doesn't support the web URL like http://ip:flatcar.ign

**Comment by pothos** [comment]
Since you control the kernel command line, you can set `ignition.config.url=` there with a config similar to https://github.com/kinvolk/lokomotive/blob/master/assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/install.yaml.tmpl but with a step that downloads `/opt/postinstall-ignition.json` from a URL. In the end it looks like you could use Matchbox if you have multiple machines to manage the configurations per IP address or MAC address: https://matchbox.psdn.io/

**Comment by silencej** [comment]
I see, will give matchbox a try.
