### ISSUE TITLE
find and replace coreos with flatcar ;)

### ISSUE THREAD

**Issue by surajnarwade** [flatcar/Flatcar#30]
I see there's systemd unit with a name `coreos-metadata.service` and also a environment variable file `/run/metadata/flatcar`  which has list of environment variables prefixed with `COREOS_`

is it intentional? or is there a plan to replace this? :smile_cat:

**Comment by pothos** [comment]
The upstream https://github.com/coreos/afterburn project has renamed these variables to a more generic `AFTERBURN_` prefix. We want to stay compatible with CoreOS for now, so we still use the same system serivce name and variable prefix.

**Comment by t-lo** [comment]
Keeping naming compatibility is intentional to ease adoption of Flatcar Container Linux, particularly given the relatively rapid EOL timeline of CoreOS Container Linux, for which we aim to provide a drop-in replacement.

That said, we might revisit naming compatibility in the (distant) future, but only at a point where it has become a legacy feature that's not in use anymore.
