### ISSUE TITLE
No documentation on Ignition or Ignition Validate

### ISSUE THREAD

**Issue by bbagwellffn** [flatcar/Flatcar#353]
Hey all, 

I was going through the website and I'm trying to use legacy CoreOS ignition configs inside of Flatcar. 

Several questions:
* What is an easy way for me to tell what version(s) of Ignition should be used for any given build of Flatcar?  I would imagine there would be some command like 'ignition -version', or a table on the website, or some way to confirm this.
* The configs I have been using are 2.2.0, and it seems there is no ignition-validate binary available on the website for this.  There is no gcc installed on Flatcar, and I'm not sure how I can build this binary from the source.  
* (More of a Roadmap question) Is Ignition what we should be using?  Is CloudInit preferred?  Is there any way we can have more informing output for poor sysadmins than "my machine is bootlooping" when there is something wrong in an Ignition file?

Thanks,

**Comment by pothos** [comment]
Hello,

all current channels use Ignition 0.34: https://kinvolk.io/flatcar-container-linux/releases/#stable-release
Yes, the currently supported specification version is not easily visible but only here: https://github.com/kinvolk/ignition/tree/flatcar-master/config

So you could use spec version 2.3.0 but the latest version the validator knows about is 2.2.0: https://github.com/kinvolk/container-linux-userdata-validator

```
./container-linux-userdata-validator -check-file myignition.json
```

(CoreOs)cloud-init is there but not actively developed, Ignition is the preferred way (through Container Linux Config YAMLs that you transpile with `ct`: https://github.com/kinvolk/container-linux-config-transpiler). Yes, error reporting with Ignition is currently not nice… even if you check the file or generate it from Container Linux Config so that it is syntactically correct it could still have a problem at runtime.

**Comment by pothos** [comment]
We have this issue about including the Ignition spec in the docs website: https://github.com/kinvolk/Flatcar/issues/281

I'll close this now and we can create a new issue for better error reporting but actually it only makes sense after updating to the latest Ignition version and implement this upstream.
