### ISSUE TITLE
Protocol "telnet" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by norve** [flatcar/Flatcar#361]
Prior to the last release, it used to be possible to run, for example: 
`curl -v telnet://towel.blinkenlights.nl:23` to open a telnet/socket connection. Right now it errors the following message:
```
* Protocol "telnet" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "telnet" not supported or disabled in libcurl
```

This was a nice to have feature as there aren't any other tools on the system for quickly troubleshooting TCP connectivity issues.

Please re-add telnet support in libcurl.

**Comment by margamanterola** [comment]
We use curl directly from Gentoo without changes.  When we updated curl to the latest version, the curl ebuild file changed from always enabling telnet, to conditionally enabling telnet (and other protocols) depending on USE flags: https://github.com/kinvolk/portage-stable/commit/d42ea0935e460dca8bc151b135e3d78f196c0c06#diff-87c1bc20b512568d3faf0582bc9289e7bf81d8febdb4da8741ac8c78fe6e9a5fL178

Whether a protocol is enabled or not depends on the protocol. e.g. ftp is enabled by default, while telnet is not. We would need to enable the telnet USE flag for curl if we want telnet support.

**Comment by oliwer** [comment]
There is a better tool than curl for this: ncat.

`ncat towel.blinkenlights.nl 23`

**Comment by tormath1** [comment]
since it's a `good first issue`, let's bring some elements to work on this:
* building a custom Flatcar image will be required to validate the changes: https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/
* once the SDK installed, we should assert that `curl` is installed without `telnet` USE flag.
```
equery-amd64-usr u net-misc/curl
...
 - - telnet           : Enable Telnet protocol support
```
* In the [making changes](https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/#making-changes) section, we should not have to modify `curl` ebuild - the `telnet` useflag needs to be set directly into `::coreos-overlay` in the `package.use` file: https://github.com/kinvolk/coreos-overlay/blob/main/profiles/coreos/base/package.use
* once the file edited, we can assert that `curl` will be reinstalled with `telnet` USE flag
```
emerge-amd64-usr -pv net-misc/curl
```
* Once emerged, we can build the image by following the step of the [developer-guides](https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/#rebuild-the-image)
* we can boot the new instance and SSH into it to validate that the issue is actually solved
* changes can be [committed](https://github.com/kinvolk/Flatcar/blob/main/contributions-git.md#commit-format) and pushed to a feature branch in order to be reviewed by the `flatcar-maintainers`

useful links:
* https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
*  example: https://github.com/kinvolk/coreos-overlay/pull/320
* [CNC](https://www.youtube.com/watch?v=X4m_JEtlVok) meetup: introduction to Flatcar contribution

**Comment by peanutduck** [comment]
@tormath1, I would like to work on this issue

**Comment by sayanchowdhury** [comment]
@peanutduck Feel free to start working on the issue. The steps mentioned above should help you understand the issue and get started. For any more queries, join our [Matrix channel](https://app.element.io/#/room/#flatcar:matrix.org).

**Comment by dongsupark** [comment]
PR https://github.com/kinvolk/coreos-overlay/pull/1099

**Comment by sayanchowdhury** [comment]
The fix is merged now and will be available in the next Alpha release https://github.com/kinvolk/coreos-overlay/pull/1099
