### ISSUE TITLE
Beta older than stable?

### ISSUE THREAD

**Issue by anguslees** [flatcar/Flatcar#371]
**Description**

https://kinvolk.io/flatcar-container-linux/releases/ currently matches what my machines are seeing, and says:

Stable - 2765.2.1
Beta - 2765.1.0

**Impact**

This concerns me in two ways:
- My beta machines are lacking recent CVE fixes.
- The version on stable machines was not tested through my beta machines first.

**Expected behavior**

I _expected_ all versions to go beta->stable.   If that's not a reasonable expectation, then that's ok - but I'd appreciate a pointer to docs explaining what I _should_ expect here.  This situation is making me question how I can use 'beta' at all.

**Comment by t-lo** [comment]
Hello @anguslees ,

please pardon the release delay the Beta channel; we are going to address the current Beta staleness in our next wound of releases in the week of March 29th.

In general, we use the alpha -> beta -> stable transition process for *major* version updates (e.g. 2605 vs. 2765 vs. 2801). Major releases ship significant changes (e.g. kernel or systemd upgrades, or major version bumps of plumbing level components) which, while thoroughly tested before release, might impact users' workloads from behaviour changes included in the new package versions. We recommend Beta canaries to anticipate these behaviour changes and to detect and report issues early (so we can address issues before the major version hits stable).

Patch-level updates include bug fixes and security fixes of upstream packages and configuration changes, but never bump the major/minor version of these, ensuring sustained compatibility with user workloads.

Having said the above, we usually aim to provide the "next" major Stable version to beta as soon as we transition any given major release to Stable. We are currently experiencing delays with the Beta release because of the recent stable transition of 2765 but will move 2801 to Beta next week, addressing the staleness. In general we aim to not let states like the current happen in the future.

**Comment by sayanchowdhury** [comment]
A new FCL Beta release 2801.1.0 was done yesterday: https://kinvolk.io/flatcar-container-linux/releases/#release-2801.1.0
