### ISSUE TITLE
Flatcar boots from wrong disk after a reboot (2765.2.2 and some prior versions)

### ISSUE THREAD

**Issue by nitramiz** [flatcar/Flatcar#404]
I apologize in advance for any missed details and wrongfully explained things. Please bear with me. (first issue)

## Description
 We have a cluster of physical machines, which we boot into Flatcar via PXE and use the `flatcar-install` script to install on disk (/dev/sda). We always stick to the Stable Flatcar releases and are currently using 2765.2.2. We provision the boxes with a simple ignition file and boot into PXE with a simple `pxelinux.cfg` config that just allows attaching a logged-in console and picks the right kernel and initrd.

## Impact
After a reboot, the box mounts root somehow on the wrong disk and data can be lost - i.e. mounts on /dev/sdb (data disk) instead of where it was installed (/dev/sda). Not always, but usually the disks swap continuously following reboots (sda -> sdb -> sda etc)

## Environment and steps to reproduce

1. **Set-up**: 

`pxelinux.cfg`:
```
default flatcar
label   flatcar

kernel flatcar/flatcar_production_pxe.vmlinuz
initrd flatcar/flatcar_production_pxe_image.cpio.gz
append console=ttyS1,115200n8 console=tty1 flatcar.autologin=tty1 flatcar.autologin=ttyS1 
```

`ignition.json` used in the `flatcar-install` script:
```
{
  "ignition": { "version": "2.3.0" },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh keys"
        ]
      }
    ]
  },
  "storage": {
    "filesystems": [
      {
        "name": "oem",
        "mount": {
          "device": "/dev/disk/by-partlabel/OEM",
          "format": "ext4",
          "label": "OEM"
        }
      }
    ],
    "files": [
      {
        "filesystem": "oem",
        "path": "/grub.cfg",
        "contents": {
          "source": "data:,set linux_append="$linux_append coreos.autologin=tty1 coreos.autologin=ttyS1 coreos.autologin=ttyS0 coreos.autologin=tty0
          set linux_console="console=ttyS1,115200n8 console=tty1"
        },
        "mode": 420
      },
      {
        "filesystem": "root",
        "path": "/etc/systemd/resolved.conf",
        "contents": {
          "source": "data:, some DNS servers"
        },
        "mode": 420
      },
      {
        "filesystem": "root",
        "path": "/etc/coreos/update.conf",
        "contents": {
          "source": "data:,%0AREBOOT_STRATEGY=off"
        },
        "mode": 420
      },
      {
        "filesystem": "root",
        "path": "/etc/ssh/sshd_config",
        "contents": {
          "source": "data:,     apply a stricter config 
        },
        "mode": 384
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "enabled": true,
        "name": "sshd.service"
      },
      {
        "enabled": true,
        "name": "sshd.socket"
      },
      {
        "enabled": true,
        "name": "docker.service"
      },
      {
        "mask": true,
        "name": "update-engine.service"
      },
      {
        "mask": true,
        "name": "locksmithd.service"
      }
    ]
  }
}
```
2. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]

Installation procedure:
```
sudo mkfs.ext4 /dev/sda
sudo mkfs.ext4 /dev/sdb
curl -O http://internal.ip/linux/flatcar/pxeconfig.ign 
sudo flatcar-install -d /dev/sda -i /home/core/pxeconfig.ign
ls -la /dev/disk/by-label (check labels)
systemctl reboot
```
And make sure everything works as expected and can ssh.
3. **Error**: [describe the error that was triggered]
The Flatcar partitions EFI-SYSTEM, OEM and ROOT have been created (and moved somehow) to the wrong disk `/dev/sdb1, 6, 9`.
## Expected behavior
After a reboot the original partitions `/dev/sdaX` remain intact and the secondary disk remains as a data disk (`/dev/sdb`).  

## Additional information
We had a major outage due to this, which we thought had resulted in data loss, but luckily no data was lost. The box was a kubernetes worker, which locked up and needed to be rebooted. We used to have the `update-engine` and `locksmithd` services enabled and running (now masked), which led to the machine coming back up and sending out a notification that it will update and reboot. The second reboot caused the above issue and we thought we had lost some critical data since the services didn't start properly. But another reboot saved the day. The second update reboot didn't manage to overwrite any of the second disk's data blocks.

We first expperienced this problem after that machine got auto-updated from `2345.3.1` to `2605.7.0`. I believe those are the correct versions. Also, we've experienced this on multiple machines and on both of our physical clusters in different locations. The machines are part of a somewhat old Supermicro 24-bay chassis (can provide more details if needed).

**Comment by pothos** [comment]
Hello,
thank you for the detailed report. You run into a tricky behavior of the Linux kernel: it will assign the device names in the order they got detected which is not stable over reboots. This is often the case for NICs or hard disks and the solution is to always refer to the devices by their stables names.
You can't assume that OS disk is always called `/dev/sda` just because it was called `/dev/sda` in the PXE boot. For disks you are already doing it right in the Ignition config where you have `/dev/disk/by-partlabel/OEM` to find the correct partition.
You should always use predictable `/dev/disk/by-SOMETHING/NAME` paths in your scripts, systemd mount units or Kubernetes configurations. There are identifiers that use the manufacturer information or the PCI location and there are identifiers that use the disk content (partition or filesystem label, UUID etc). If both disks are the same and you don't care, you can the `/dev/sdX` name to format the disk and from that point on use the content-based identifiers.

All works as expected and I'll close this here but of course you can ask further questions.

In case it helps, here an example for an Ignition config (CLC YAML) which partitions the disk that is called `/dev/sdb` and from that point on uses the content-based identifiers to format this partition with a filesystem and to mount this filesystem. This is not an answer to your problem but just servers the purpose of showing how the order of actions works in case you can't use `/dev/disk/by-…` for the very first step:

```
storage: 
  files: 
    - path: /etc/systemd/system/myvolume.mount 
      filesystem: root 
      mode: 0644 
      contents: 
        inline: | 
          [Unit] 
          Description=MyVolume Mount 
          Before=local-fs.target 
          [Mount] 
          What=/dev/disk/by-partlabel/myvolume 
          Where=/myvolume
          Options=noatime 
          [Install] 
          WantedBy=local-fs.target
  disks: 
    - device: /dev/sdb 
      wipe_table: true 
      partitions: 
        - label: myvolume 
  filesystems: 
    - mount: 
        device: /dev/disk/by-partlabel/myvolume 
        format: ext4 
        wipe_filesystem: true 
        label: myvolume 
```

**Comment by nitramiz** [comment]
Wow, thanks for the prompt response! Thanks for the clarification and the tip!

 I guess that makes sense and explains our case. I don't remember if the first box we saw the issue had been rebooted before it needed a reboot due to that lockup. It sounds plausible that a few times in a row the same disk (with the OS) was named `/dev/sda` but after that problematic reboot, that disk became `/dev/sdb`. 
 
 So, would you advise after formating the two disks with `mkfs.ext4` in step 2 above, we should also label the disks (e.g. `tune2fs -L FLATCAR /dev/sda`, `tune2fs -L DATA /dev/sdb`) and then use the `flatcar-install` script with `-d /dev/disk/by-label/FLATCAR`  instead of `/dev/sda`?
 
 Thanks!

**Comment by pothos** [comment]
Within the same _boot_ it does not matter much, but maybe you need logic to find the disk that's better for the OS or the data. Also, you should not run mkfs on the disk which you use for flatcar-install because this created filesystem will be overwritten anyway. I would change `mkfs.ext4` to `mkfs.ext4 -L mylabel` but all these steps are not your problem, your problem happens afterwards when you mount your data partition (you didn't share this part).

**Comment by nitramiz** [comment]
Hmm, ok. I'm not quite sure I understand how to handle that consistency - keep the OS disk as an OS disk and the data disk as a data disk.

I guess we should not use `dev/sdb` in the below snippet, but rather a `/dev/disk/by-label/DATA`? 

We use a very basic OpenEBS setup for the data disk:
```
mkfs.ext4 /dev/sdb
tune2fs -L DATA /dev/sdb

cat <<EOF > /etc/systemd/system/mnt-openebs.mount
[Unit]
Description=/dev/sdb disk mount

[Mount]
What=/dev/sdb
Where=/mnt/openebs
Type=ext4
Options=defaults

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload && systemctl enable --now mnt-openebs.mount
```

**Comment by pothos** [comment]
Yes, you found your problem (or at least one of them), `What=/dev/sdb` is not stable over reboots and should be by-label/DATA or similar.

**Comment by nitramiz** [comment]
Got it! Thanks. I'll have some time in the next couple of weeks to test. Very much appreciate the help and will report any further developments:)  🙌🏻
