### ISSUE TITLE
[RFE] - Support Azure Generation 2 VMs

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#417]
## Current situation

The Flatcar offers on Azure (both free and commercial) support Gen1 VMs only. Flatcar is not release tested on Gen2 VMs.

## Impact

Flatcar users need to provision OS images in a manual way / create their own VM images on Azure in order to deploy to Gen2. Users risk running into potential issues that affect Gen2 only.

## Ideal future situation

Flatcar has release tests running on both Gen1 and Gen2 VMs. Flatcar offers are available for Gen1 and Gen2.

## Progress
- [x] https://github.com/kinvolk/coreos-overlay/pull/1198
- [x] https://github.com/kinvolk/mantle/pull/214
- [x] https://github.com/kinvolk/flatcar-scripts/pull/146

## Additional information

See https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2

**Comment by jepio** [comment]
To upload gen2 images to azure we need to update our azure-sdk-for-go in mantle. Started looking into that.

Current VHDs, uploaded manually (https://github.com/kinvolk/flatcar-cloud-image-uploader/blob/master/azure-flatcar-image-upload/upload_image.sh) get stuck during boot because of:
```
[   15.010516] ignition[650]: failed to open config device: open /dev/disk/by-id/ata-Virtual_CD: no such file or directory
```

**Comment by jepio** [comment]
Found an ignition PR that enables gen2 support, backported it and going to submit it into our ignition (https://github.com/coreos/ignition/pull/1241).

That's enough to get working boot. I see the following in boot log on a gen2 vm, but booting the same vhd as gen1 shows nothing:
```
[   14.375075] audit: type=1400 audit(1629206827.419:91): avc:  denied  { integrity } for  pid=1 comm="systemd" lockdown_reason="/dev/mem,kmem,port" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=lockdown permissive=1
[   14.465219] audit: type=1400 audit(1629206827.508:92): avc:  denied  { bpf } for  pid=1 comm="systemd" capability=39  scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=capability2 permissive=1
[   14.487870] audit: type=1400 audit(1629206827.508:93): avc:  denied  { perfmon } for  pid=1 comm="systemd" capability=38  scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=capability2 permissive=1
```

**Comment by jepio** [comment]
We need to upgrade the default Azure VM size to `Standard_DS2_V2` (previously `Standard_D2_V2`) because the previous one doesn't support Gen2 VMs (https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2).

I will probably introduce a kola switch `--azure-vm-generation`, but i wonder how to integrate this with jenkins.

**Comment by jepio** [comment]
The audit denied entries don't show up with current images.

In the meantime the CI has started running nightly tests on Azure Gen1 and Gen2 VMs, and all tests are green. So everything works as intended :)

**Comment by jepio** [comment]
The only thing left to do is to officially publish the image as a Gen2 image in the marketplace. Let's see if we manage to do that in time for next weeks release.

**Comment by AlexHunterCodes** [comment]
Does this mean Gen2 images for Azure will work well in Gen2 Hyper-V VMs, or will this still require manual image customisation/installation as before?

**Comment by jepio** [comment]
Can you tell me more about the customisations required for Gen2 Hyper-V VMs, I wasn’t aware that there was an issue.

**Comment by AlexHunterCodes** [comment]
The original post says that people have previously been building their own Flatcar images to run in Azure Gen2 VMs because these were not officially provided.

Hyper-V images are provided, but there is barely any documentation referencing their existence (which struck me as odd since the MS acquisition, then again it looks like standalone Hyper-V is being killed off anyway) so I assumed these images were unsupported to an extent, and purely provided for convenience. Last time I tried one of those images in a Gen2 Hyper-V VM it seemed clearly unfinished (at the time anyway), so I've been running Gen1 instead. 

So I'm asking if this issue is purely talking about _Azure_ Gen2-specific support (SDK, cloud provisioning APIs, etc.) or if it's talking about Azure _Gen2_-specific support (like UEFI, Secure Boot, new paravirtualised devices, etc.) which would also benefit Hyper-V Gen2 hosts?

**Comment by jepio** [comment]
> The original post says that people have previously been building their own Flatcar images to run in Azure Gen2 VMs because these were not officially provided.

That was what we thought, but it turned out that previous releases VHDs boot looped on Azure Gen2 VMs and couldn't be used.

> Hyper-V images are provided, but there is barely any documentation referencing their existence (which struck me as odd since the MS acquisition, then again it looks like standalone Hyper-V is being killed off anyway) so I assumed these images were unsupported to an extent, and purely provided for convenience. Last time I tried one of those images in a Gen2 Hyper-V VM it seemed clearly unfinished (at the time anyway), so I've been running Gen1 instead.

I understand where you're coming from, but keep in mind that Flatcar is a community project. The MSFT acquisition has not changed that. Some platforms are better documented and supported, there's no denying that, but over time things get better as users contribute issues/documentation/bugfixes.

The Hyper-V images were inherited from CoreOS, but they did not see much work there either since they were introduced in 2014.

> So I'm asking if this issue is purely talking about Azure Gen2-specific support (SDK, cloud provisioning APIs, etc.) or if it's talking about Azure Gen2-specific support (like UEFI, Secure Boot, new paravirtualised devices, etc.) which would also benefit Hyper-V Gen2 hosts?

In this issue the only thing that was tackled was Azure Gen2 CI, and ignition provisioning.

Of the items you listed that are common to both Azure and Hyper-V Gen2 VMs:
* UEFI support works
* new paravirtualised Hyper-V devices work
* SecureBoot unfortunately doesn't work which is partially due to us carrying a very old fork of Grub. I hope we can tackle this one in the future.

I would be interested in finding out how you work with Hyper-V Flatcar VMs, maybe we can turn some of that into some new documentation. What I don't really know is how one would provision configuration to Hyper-V VMs, since I don't see a good way to run "ignition". The way I think I would do it is boot our ISO/hyper-V VHD in a VM with an additional disk, run `flatcar-install -d /dev/sdb -i ignition.json -o ""` on that disk and then clone that disk to create new hyper-V VMs. I'm sure there are issues but that would be a start. Do you have other suggestions?

**Comment by AlexHunterCodes** [comment]
> I understand where you're coming from, but keep in mind that Flatcar is a community project. The MSFT acquisition has not changed that. Some platforms are better documented and supported, there's no denying that, but over time things get better as users contribute issues/documentation/bugfixes.

Oh sure, absolutely. Reading my comment back, sorry for the tone, didn't mean to come across like that. I just didn't understand why you were going to the effort of building CI images for a platform that appeared to be undocumented and somewhat abandoned. Couldn't tell if it was undocumented just because nobody has gotten around to writing it yet, or because the project explicitly decided to drop Hyper-V support at some point. Inheriting them from CoreOS makes a lot more sense.

> I would be interested in finding out how you work with Hyper-V Flatcar VMs, maybe we can turn some of that into some new documentation. What I don't really know is how one would provision configuration to Hyper-V VMs, since I don't see a good way to run "ignition". The way I think I would do it is boot our ISO/hyper-V VHD in a VM with an additional disk, run `flatcar-install -d /dev/sdb -i ignition.json -o ""` on that disk and then clone that disk to create new hyper-V VMs. I'm sure there are issues but that would be a start. Do you have other suggestions?

I started off basically doing that (except I used .iso disc images), and I'd have a provisioning server SSH in to complete the process, similar to how Packer does it. But I've also experimented with iPXE and pulling configs from a URL, and using WSL2 to mount and customise VHDs built from a template.

Reached a point where I'm building and tearing down clusters more frequently, and I'd like to build something more robust that I can use with my existing Packer/Terraform workflow. My interest in this PR was the possibility of upgrading to Gen2 VMs and potentially eliminating Packer from the process entirely. Hyper-V's key-value guest integration seems to be the best candidate for pushing configs in from the host, but I've never used it before and wouldn't know where to start in terms of integrating with Ignition.
