### ISSUE TITLE
Perl is broken in development container

### ISSUE THREAD

**Issue by DRKV333** [flatcar/Flatcar#490]
## Description

The version of perl included in the current Flatcar development container was compiled wrong, and will immediately segfault under certain condition. This is actually a really old issue from CoreOS (coreos/bugs#2369), that was originally ignored, and has just been noticed and fixed in upstream not long ago (Perl/perl5#18739). This issue might be caused by the same problem: #307. Interestingly, a simple `echo 'print("Hello, World!\n");' | perl` is indeed not enough to trigger the segfault.

## Impact

I'm trying to automate the build of zfs for Flatcar, and having to patch and rebuild perl every time is a bit of a pain. (https://github.com/lorenz/torcx-zfs/blob/cb9ad1fef25cda4dcb18935883151113af2f791d/build.sh#L13-L15)

## Environment and steps to reproduce

1. Enter development container with `systemd-nspawn`, as usual. 
2. Run `perl -V`
3. Observe segfault.

```
Attempt to free unreferenced scalar: SV 0x55f7886da390 at /usr/lib64/perl5/5.26.2/strict.pm line 38.
Segmentation fault
```

**Comment by jepio** [comment]
Thanks, I dove into the perl-cross scripts and figured out what's going on:
If the `optimize` variable is passed by the user, then `perl-cross/cnf/configure_tool.sh` won't append `-fwrapv -fno-strict-aliasing` to it. Since we touch `optimize` (https://github.com/kinvolk/portage-stable/blob/main/dev-lang/perl/perl-5.26.2.ebuild#L505), we need to take care of passing fwrapv and fno-strict-aliasing ourselves. I'll try to get the fix into gentoo as well.

**Comment by jepio** [comment]
So the fix will be part of all channels this week, and the upstream PR has been submitted. I'll go ahead and close this .

Thanks for the issue, its interesting to see what people use torcx for. We're starting to think about replacing torcx with something else that will remain compatible but be better maintained and documented (https://github.com/kinvolk/Flatcar/issues/443).
