### ISSUE TITLE
Missing (IPv4) traceroute

### ISSUE THREAD

**Issue by norve** [flatcar/Flatcar#50]
The IPv4 `traceroute` utility appears to be absent from the system, although `/usr/sbin/traceroute6` exists. I'm not sure if this was inherited from the original CoreOS Container Linux.

**Comment by dongsupark** [comment]
Yes, that was inherited from CoreOS, as well as upstream Gentoo.

As far as I understand from the [corresponding discussion](https://github.com/coreos/bugs/issues/1572#issuecomment-285170687
), users can use `tracepath` included in `net-misc/iputils`, instead of `traceroute`. 
For some reason, however, the `tracepath` binary file has not been included in Flatcar images.
We can get it included in the next Flatcar releases, including stable.
Does it make sense?

**Comment by dongsupark** [comment]
Filed https://github.com/flatcar-linux/coreos-overlay/pull/237

**Comment by dongsupark** [comment]
Stable 2345.3.1 and Beta 2411.1.1 were just released, so this issue should be fixed.
Alpha and Edge still have the issue, so I will leave this issue open.

**Comment by dongsupark** [comment]
It should be available since Alpha 2466.0.0 and Edge 2466.99.0.
