### ISSUE TITLE
Version info of 2905.2.4 is 2905.2.3

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#522]
## Description

Version info of 2905.2.4 is 2905.2.3

## Environment and steps to reproduce

1. Install VM 2905.2.4.
2. cat /etc/os-release. Please refer to below screen shot.

<img width="588" alt="Screen Shot 2021-09-30 at 9 46 23 AM" src="https://user-images.githubusercontent.com/27849915/135375329-773a159e-c1e0-404e-bddb-3ecd72fa7f8d.png">

**Comment by Winnie81** [comment]
![Uploading Screen Shot 2021-09-30 at 10.38.22 AM.png…]()
Kernel is 5.10.61, not 5.10.67.

**Comment by tormath1** [comment]
Hi @Winnie81, 

This behavior is caused by https://github.com/flatcar-linux/Flatcar/issues/520; we identified a regression issue in the Linux Kernel 5.10.67.

> On Sep. 28th (Tue), we reverted on Nebraska, the update service, the default version of Stable and Alpha channels back to 2905.2.3 and 2983.0.0 respectively. We also have set the current symlinks on *.release.flatcar-linux.net to the previous versions.

That's why you have such a behavior - we are actively working on the new release to include Linux Kernel 5.10.69 which holds the fix and a test case has been added to prevent this kind of issue in the future (https://github.com/flatcar-linux/scripts/pull/153).

I close your issue as duplicated to the #520 one.
