### ISSUE TITLE
Flatcar failing to deploy on Azure Dv5 and Ev5 

### ISSUE THREAD

**Issue by anhvoms** [flatcar/Flatcar#550]
## Description

Azure flatcar images fail to provision on the new Dv5 and Ev5 VMs. These series have the SRIOV interface coming up with mlx5_core driver instead of mlx4_en. Current flatcar images exclude SRIOV interfaces in /usr/lib/systemd/network/yy-azure-sriov.network by matching for mlx4_en driver. mlx5_core needs to be added as well

## Impact

Azure flatcar images fail to provision on the new Dv5 and Ev5 VMs.

## Environment and steps to reproduce

1. **Set-up**: Azure/Standard_D2ds_v5
2. **Task**: N/A
3. **Action(s)**: Deploy a new VM using kinvolk flatcar-container-linux alpha 2643.0.0
4. **Error**: VM deployment timeout. 

## Expected behavior

VM deployed successfully.

## Additional information

Please add any information here that does not fit the above format.

**Comment by pothos** [comment]
Hi,
thanks for reaching out. That's strange, recent versions should have it added already: https://github.com/flatcar-linux/init/blob/flatcar-master/systemd/network/yy-azure-sriov.network (where recent is since Dec 2020, as this change is in Stable since then https://www.flatcar-linux.org/releases/#release-2605.9.0 and in Alpha since Oct 2020 https://www.flatcar-linux.org/releases/#release-2671.0.0)
Will need to reproduce it and debug.

In general we should investigate if the network setting can be set from afterburn or waagent, by creating a networkd unit matching with the MAC address from the instance metadata (`"macAddress"`) to set it `Unmanaged`, including a negative matching for `Driver=!hv_netvsc` because eth0 has the same MAC address.

**Comment by pothos** [comment]
Can't reproduce it when deploying a new instance. I used v4 because v5 is not available, but both use the same driver anyway:
```
$ networkctl status enP13620s1
● 3: enP13620s1                                                                
                     Link File: /usr/lib64/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: enslaved (unmanaged)
                  Online state: unknown
             Alternative Names: enP13620p0s2
                          Path: acpi-VMBUS:00-pci-3534:00:02.0
                        Driver: mlx5_core
                        Vendor: Mellanox Technologies
                         Model: MT27710 Family [ConnectX-4 Lx Virtual Function]
```

I believe the instance is not on the latest version or something else is wrong. Can you paste `/usr/share/flatcar/release`?

**Comment by anhvoms** [comment]
My apologies. I did not try with latest. I can confirm latest does not have the issue when deploying on v5. Thanks folks!

**Comment by anhvoms** [comment]
My apologies. I did not test with latest. The latest alpha image worked for me and indeed networkctl is showing the SRIOV nic as unmanaged.

**Comment by t-lo** [comment]
@anhvoms Thanks for sharing the update; could I please bug you to provide the version it _did not_ work with and update the issue summary (for documentation purposes)?

**Comment by anhvoms** [comment]
@t-lo Updated. The images tested were:
kinvolk flatcar-container-linux-free alpha 2643.0.0
kinvolk flatcar-container-linux-free beta 2643.1.0
kinvolk flatcar-container-linux-free stable 2605.7.0

**Comment by pothos** [comment]
I made 3 test runs with v5 and in one case I had no network. There may be something going on but the interactive serial console did not work - next time it happens I'll see to get the read-only serial output which could contain a hint.

**Comment by pothos** [comment]
There are two follow-up times which we can track now:
- set the NIC as unmanaged from waagent or afterburn based on the metadata instead of hardcoding drivers https://github.com/flatcar-linux/Flatcar/issues/554
- run the release validation on more instance types https://github.com/flatcar-linux/Flatcar/issues/553
