### ISSUE TITLE
Missing "New Package Request" issue template

### ISSUE THREAD

**Issue by Patricol** [flatcar/Flatcar#736]
## Description

Based on older issues, it seems there used to be an actual template for issues requesting new packages; as also suggested by the `adding-new-packages.md` file.

The template appears to be missing. I believe templates are managed outside of git; so I can't point to a commit where it was removed.

**Comment by Patricol** [comment]
As a side note, is this the right place to request `qemu-guest-agent`? Or is there a more specific place for packages that are only needed in certain distribution images?

**Comment by pothos** [comment]
An issue here for qemu-guest-agent is good, thanks
(Edit: I think the agent isn't really OEM specific because QEMU gets used on different platforms and instead of the Flatcar OEM ID we could try to use the systemd virtualization detection)

**Comment by jepio** [comment]
What other platforms would need the qemu-guest-agent, openstack? Do you suggest making it part of the /usr partition and then having a unit with `ConditionVirtualization=qemu` run it?

**Comment by pothos** [comment]
Yes, the QEMU "OEM image" has no real customizations except the autologin setting and the fact that it is a qcow2 image. The generic image is quite good for usage with QEMU and is easy to customize through mounting it without any conversion, that's why I wouldn't want to make the QEMU "OEM image" more mandatory by introducing extra features that are otherwise not available.
