### ISSUE TITLE
Kola test google.kubernetes.basic.docker.v1.3.4_coreos.0 fails with new Alpha release

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#79]
**Description**
The `kola` test for validating an old Kubernetes version on GCE, `google.kubernetes.basic.docker.v1.3.4_coreos.0`, reproducibly fails with the new Alpha release.

**Impact**
Running Kubernetes 1.3.4 (via `torcx`) on GCE is not tested in the release tests.

**Environment and steps to reproduce**

1. **Set-up**: check out `mantle`, branch `flatcar-master`, and build.
2. **Task**: Validate Kubernetes 1.3.4 to run on Flatcar GCE image
3.**Action(s)**: `kola run google.kubernetes.basic.docker.v1.3.4_coreos.0 --platform gce [...]`
4. **Error**: The installation script times. Increasing the timeout (https://github.com/flatcar-linux/mantle/blob/flatcar-master/kola/tests/kubernetes/setup.go#L313) to 20 mins still has the test time out.

**Expected behavior**
The installation script succeeds and the test proceeds.

**Comment by pothos** [comment]
1.3.4 refers to the Kubernetes version, it uses the current Docker version. The control plane does not come up, not sure why.

**Comment by t-lo** [comment]
Thanks, updated the description accordingly.

**Comment by margamanterola** [comment]
This works in beta, which has docker version 18.06.3-ce, but fails in alpha, which has docker version 19.03.8.

This error in the docker journal points to the problem: 
`env[1027]: time="2020-04-14T16:53:58.069045607Z" level=error msg="Handler for POST /containers/4d04a2ca19f80b6c8583e294a2bea1abe5048835c29afe945ba696ee2fa608d8/start returned error: can't join IPC of container 1e0c0a5e0db08aa37f0077f82ca15298fa53e3a4615d86e0a8c0176f62bdc927: non-shareable IPC (hint: use IpcMode:shareable for the donor container)"`

Docker 19.03 moved to using [private ipc by default](https://github.com/moby/moby/pull/35621), so that explains the breakage.

Our test is running the hyperkube 1.3.4 image, which is from August 2016. 

I think [this kubernetes commit](https://github.com/kubernetes/kubernetes/commit/1dca64fffd344c770e2380100ee835cc6281060e) from November 2018 (first released in 1.14) sets the right flag to make kubernetes work with docker 19.03 or higher.

I'm not sure if we can modify our test case to pass this as a flag to docker, I looked around and couldn't figure out how, but there might be a way.  Alternatively, it might make more sense to adapt our test to a newer hypercube image... I doubt there are a lot of people out there wanting to use the latest flatcar image to run a 4 year old Kubernetes image.

**Comment by margamanterola** [comment]
Ok, I'm working on updating the test.

The source we're using (quay.io) stopped including k8s versions after 1.10.  They recommended the switch to [Google's images](gcr.io/google-containers/hyperkube) back then. I've found a bunch of other projects that were using quay and moved to gcr. I'll do that together with the move to 1.14.
