### ISSUE TITLE
Failed to allocate directory watch: Too many open files

### ISSUE THREAD

**Issue by necipakca** [flatcar/Flatcar#830]
Sometimes on my k8s cluster I am getting this output when I login to node and try to do basic linux commands.
I already try to increase fs.inotify.max_user_watches but result is same.
The issue continues until restart OS.

My Environment is ; 
Bare Metal
K8s - > 1.22.8
Linux node6 5.15.32-flatcar #1 SMP Tue Apr 5 17:17:31 -00 2022 x86_64 Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz GenuineIntel GNU/Linux

**Comment by jepio** [comment]
Hi @necipakca,
What flatcar version are you using? Do you run very many pods/containers on that node? Have you tried increasing `fs.inotify.max_user_instances` sysctl to a greater value?

**Comment by necipakca** [comment]
What flatcar version are you using: Flatcar 3139.2.0
Do you run very many pods/containers on that node : Yes I have many pods on machines approximately over the 200.

Have you tried increasing fs.inotify.max_user_instances sysctl to a greater value?

Nope I did not tried  to increase "fs.inotify.max_user_instances" parameter. I don't have same issue now. When it happen I will try the parameter and let you know the result.

**Comment by tylerauerbeck** [comment]
@necipakca We've seen similar issues. I believe this was related to a containerd issue (I'll see if I can dig up the issue link), but increasing `fs.inotify.max_user_instances` has resolved the issue in our case. The fix for this issue landed in containerd 1.6 and I believe was in the process of being backported to 1.5. At this point, we haven't seen any issues on our nodes with flatcar 3227 (containerd 1.6.6)

**Comment by jepio** [comment]
The same fixes were backported to containerd [v1.5.12](https://github.com/containerd/containerd/releases/tag/v1.5.12), could it be that you're on Flatcar 3139.2.0?

**Comment by necipakca** [comment]
> v1.5.12

Yes you are right same issue. 
Ok I am kindly closing this issue after we distribute new Flatcar version probably it will be fixed.

Thanks a lot
