### ISSUE TITLE
[RFE] kernel updates in Flatcar stable and beta releases

### ISSUE THREAD

**Issue by defo89** [flatcar/Flatcar#853]
## Current situation

Kernel version is updated in stable/beta/alpha channels simultaneously.

## Impact

Last update to `5.15.63` resulted in https://github.com/flatcar-linux/Flatcar/issues/847. Despite running Flatcar beta in QA environment, there was no good possibility to catch and report this issue in a timely manner.

## Ideal future situation

Update kernel in rolling manner same as it's done with other important components (systemd, containerd, docker, ignition)

**Comment by t-lo** [comment]
Thank you for speaking up - usually we would argue that kernel patch level releases only contain bug fixes (for LTS kernels, no less) and therefore it's better to update than not to. However, recent events (which you've referenced) show that we need to apply more care and be more conservative with updating Stable.

We are therefore planning to introduce a week of delay between Beta and Stable releases in the future, particularly if these ship the same kernel version (which is likely since we rely on LTS kernel series nowadays). This will provide more time for users with Beta canaries to report back on kernel issues.

**Comment by t-lo** [comment]
We're putting this into practice with the ongoing release (Beta-3346.1.0, Alpha-3374.0.0) and will release the respective Stable version at least one week later. This pattern will also go into our releases retrospective later this year (where we'll rough-draft the 2023 releases) and we'll make sure to follow it from now on.

@defo89  Please let us know if this satisfies your inquiry and we can close this issue. (we will of course continue to track #847 until that regression is fixed).

**Comment by defo89** [comment]
@t-lo thank you for improving the process and making it transparent. This indeed will win us more time to catch potential issues.
