### ISSUE TITLE
openssl version still reports old version inspite of CVE-2022-3602 and CVE-2022-3786 being fixed

### ISSUE THREAD

**Issue by skshandilya** [flatcar/Flatcar#890]
## Description
openssl version still reports old version (3.0.2) but the release page reports that the
CVE-2022-3602 and CVE-2022-3786

## Impact

This is critical CVE, that needs an urgent fix

## Environment and steps to reproduce
Install flatcar on a VMware setup
testuser@localhost ~ $ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3227.2.4
VERSION_ID=3227.2.4
BUILD_ID=2022-10-27-1321
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3227.2.4 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3227.2.4:*:*:*:*:*:*:*"
testuser@localhost ~ $ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

## Expected behavior
openssl version should report 3.0.7 the version the two critical CVE's have been fixed

**Comment by tormath1** [comment]
Hello @skshandilya,

Thanks for the report. As mentioned in this conversation[^1]: OpenSSL has been built with the patches required to fix the vulnerability.

Flatcar is build from package sources, so we can easily apply patches at the build time: https://github.com/flatcar/coreos-overlay/blob/stable-3227.2.4/dev-libs/openssl/openssl-3.0.2-r1.ebuild#L56

That's why the version still appears "old", because we essentially applied the patch on the concerned code.

[^1]: https://github.com/flatcar/Flatcar/issues/886#issuecomment-1300791216

**Comment by pothos** [comment]
The update to 3.0.7 is queued now that it is available from upstream and will be part of the next releases so that we can drop the downstream security patch.
As said in the other issue, Flatcar does not even seem to be vulnerable by testing with https://github.com/colmmacc/CVE-2022-3602

**Comment by t-lo** [comment]
To elaborate on our motivation to go with a single patch instead of a version jump, OpenSSL regularly introduces unrelated changes even in their patch level releases (say, from 3.0.3 to 3.0.7) that tend to increase risk of breakage. We want our users to update swiftly w/o risk, so we backport.
