### ISSUE TITLE
How do you increase Available Entropy?

### ISSUE THREAD

**Issue by bignay2000** [flatcar/Flatcar#892]
## Description
How would I go about increasing Entropy in Flatcar?
I have a Flatcar Linux VM that is showing 256 entropy_avail.  

```
cat /proc/sys/kernel/random/entropy_avail
256
```
## Impact

Concerned adding additional docker containers may cause instability.

## Environment and steps to reproduce

Flatcar Linux VM on VMWare ESXi 7.0.3
Flatcar Container Linux by Kinvolk stable 3227.2.4 for VMware
Linux  5.15.70-flatcar #1 SMP Thu Oct 27 12:53:14 -00 2022 x86_64 Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz GenuineIntel GNU/Linux

8 vCPU
64 GB RAM

VM runs 2 Gitlabs, Jenkins, LDAP, Nexus 3, influxdb,  containers.  Currently no stability issues. 

## Expected behavior

Entropy is considered to be low in Linux when it is below 1000?

**Comment by pothos** [comment]
How long is the system up when you see this and can you give a link about the number 1000? My Fedora system also shows 256.

In general https://www.zx2c4.com/projects/linux-rng-5.17-5.18/inside-linux-kernel-rng-presentation-sept-13-2022.pdf is a good read on the properties of the random generator.
In short: entropy only matters at boot and even there it doesn't have to be externally supplied because the kernel does the jitter dance.

**Comment by bignay2000** [comment]
Looks like this is expected behavior in Linux to have 256 entropy.
