### ISSUE TITLE
AMI Source `075585003325/Flatcar-stable-2905.2.6-hvm` in us-east-2 unavailable

### ISSUE THREAD

**Issue by jrodriguez-tivo** [flatcar/Flatcar#947]
## Description

We use AMI source "075585003325/Flatcar-stable-2905.2.6-hvm" for flatcar community version 2905.2.6 on AWS.
Starting new instances from our tooling exposed that this AMI is not available in us-east-2.

## Impact

Unable to deploy new systems.  AMI source `075585003325/Flatcar-stable-2905.2.6-hvm` unavailable.

## Environment and steps to reproduce

1. Deploy a new EC2 in us-east-2, attempt to find AMI via source - `075585003325/Flatcar-stable-2905.2.6-hvm`

## Expected behavior

Launching instances continues to work with AMI Source - `075585003325/Flatcar-stable-2905.2.6-hvm`

## Additional information

In searching came across https://github.com/flatcar/Flatcar/issues/456 which looks to be similar issue.
AMI is available in us-west-2, however, not available in us-east-2

Oregon (us-west-2), shows expected - ✔️ 
![image](https://user-images.githubusercontent.com/37548975/212417994-fafa5987-dfc5-477e-9c35-4b47888cf180.png)

Ohio (us-east-2) does not show expected - ❌  
![image](https://user-images.githubusercontent.com/37548975/212418230-fed3f1d9-ac89-4d73-ab33-72819690c558.png)

**Comment by jepio** [comment]
#456 was a publishing issue. The 2905.2.6 AMI in us-east-2 has been deregistered due to our retention policy (https://flatcar-linux.org/docs/latest/installing/cloud/aws-ec2/#release-retention-time). From our AMI GC logs I see that the AMI in question has been deregistered after a 3 week soft-delete period (during which this could have been undone easily):
> 2023-01-12T05:47:13Z prune:us-east-2: Obsolete image "Flatcar-stable-2905.2.6-hvm"/"ami-0adaa453e3c7f2503": 445 days old
> 2023-01-12T05:47:14Z platform/api/aws: Deregistered existing image ami-0adaa453e3c7f2503

The source vmdk is kept on our release servers indefinitely https://stable.release.flatcar-linux.net/amd64-usr/2905.2.6/, are you able to go through self-publishing the AMI?

Is there something preventing you from updating to a newer Flatcar release?

**Comment by jrodriguez-tivo** [comment]
We're going to host our own copy of the AMI.

The etcd changes that were coming in w/ 
https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/upgrades/upgrade_3_5.md were primary blocker in upgrading.

**Comment by pothos** [comment]
If you use the inbuilt `etcd-member.service` you can set the etcd version through a unit drop-in:
```
[Service]
Environment="ETCD_IMAGE_TAG=v3.4.0"
```

**Comment by jrodriguez-tivo** [comment]
Thanks all - we've switched to self hosted AMIs.
